# Generated by Django 3.0.1 on 2019-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=16)),
                ('timestamp', models.CharField(max_length=10)),
                ('handle', models.CharField(max_length=64)),
                ('tweet', models.CharField(max_length=140)),
            ],
        ),
    ]
